### ISSUE TITLE
Question about oracle schema linking

### ISSUE THREAD

**Issue by jc-ryan** [THU-BPM/ISESL-SQL#2]
Nice work！
I have noticed that  the oracle schema linking information could bring a huge improvement for Spider and Spider-SYN in section3.6, I wonder that where does the  oracle schema  information come from for both of two datasets. Could you offer a link please? 
(I guess that the  oracle schema  information of Spider come from SLSQL(EMNLP2020), and how about Spider-SYN? )

Besides, could you please offer more details about how you directly change the implicit graph matrix A(𝑡) in Eq. 7 based on the oracle information, becaucse I want to try this by myself. Thanks a lot.

Best wishes!

**Comment by exlaw** [comment]
Thanks for your interest in our work.
We get the oracle schema information from SLSQL(EMNLP2020). The spider-syn is generated by synonym substitution for the spider development set, so we use the same schema linking information as the spider development set.

Since the implicit graph matrix A(𝑡) in Eq. 7 is a matrix of weights between text and schema,  so you only need to set the weight to 1 if there are oracle schema linking occurrences and 0 otherwise.

**Comment by jc-ryan** [comment]
> Thanks for your interest in our work. We get the oracle schema information from SLSQL(EMNLP2020). The spider-syn is generated by synonym substitution for the spider development set, so we use the same schema linking information as the spider development set.
> 
> Since the implicit graph matrix A(𝑡) in Eq. 7 is a matrix of weights between text and schema, so you only need to set the weight to 1 if there are oracle schema linking occurrences and 0 otherwise.

Okay, I got it, thanks!
